### ISSUE TITLE
about radio buttons and checkbox

### ISSUE THREAD

**Issue by fischer321** [UXAspects/UXAspects#1157]
Hi,

I 'd like to know if the radio buttons and checkox of UX Asepects can be used in Angular FormGroup? Thanks

**Comment by ashley-hunter** [comment]
Hi,

Yes, both these controls support both template driven forms and reactive forms, eg:

https://plnkr.co/edit/7pZmWoD7w94LXuX4l550?p=preview

Thanks

**Comment by fischer321** [comment]
Thanks for your answer, but only checkbox samples, how about 2 radio buttons with forn control samples? I tried 2 radio buttons in form control, but it doesn't work!

**Comment by ashley-hunter** [comment]
Ah ok, no problem, yes the radio buttons will work with `ngModel`, however not currently with reactive forms. I will raise a ticket to add this for you.
