### ISSUE TITLE
About 2 radio buttons with form control issue

### ISSUE THREAD

**Issue by fischer321** [UXAspects/UXAspects#1159]
At present, I tried to use UX radio buttons with form control, it has two radio buttons in a group, 
The code is like following.
https://next.plnkr.co/edit/rW7ibkMOK50v6Y6p?preview

but it doesn't work! The radio buttons check states are wrong, do you know why?

**Comment by donna-marijne** [comment]
Yes, you have bound the `value` property to a static value. I've updated your plunker to pull the current value from the FormGroup instead:

https://next.plnkr.co/edit/2hBuLttfRzcswkyu

Does that help?

**Comment by fischer321** [comment]
Thanks, It helps!
