### ISSUE TITLE
toggle button will  be trigged twice by mistake in Edge

### ISSUE THREAD

**Issue by riffling** [UXAspects/UXAspects#1318]
**Version**: @ux-aspects/ux-aspects:1.6.0, AngularJS 

**Link**: https://pages.github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/#/ui-components/buttons#toggle-buttons-ng1-component
https://github.com/UXAspects/UXAspects/blob/82aafe855433a5b5413941fee8cd32015873cc66/docs/app/pages/components/components-sections/input-controls/toggle-switch-ng1/snippets/sample.html

**How we use**
<toggleswitch style="float: right;margin-right: 40px;" ng-model="pageOption.populate" ng-click="populateVolumes();" ng-disabled="autoFillDisable()">{{'select-volume-populate-btn' | translate}}</toggleswitch>

**Summitter**
yong-jie.gong@microfocus.com
peng-qi.shi@microfocus.com

**Comment by donna-marijne** [comment]
Thanks for the report, the AngularJS components are deprecated now since we have Angular replacements, but I will accept a PR for a fix if you put one together.

**Comment by riffling** [comment]
Hi Donna
I noticed you have closed this Defect. any plan to provide the fix  in AngularJS version?

**Comment by donna-marijne** [comment]
No, see comment above, but you are welcome to provide a fix.
