### ISSUE TITLE
Date & Time Picker example throwing error

### ISSUE THREAD

**Issue by praveen2k10** [UXAspects/UXAspects#798]
Date & Time Picker example which is refered on https://uxaspects.github.io/UXAspects/#/components/date-time-picker#date-time-picker page throws error.
Please let me know if this error can be ignored.

Steps to reproduce:
1. Open https://uxaspects.github.io/UXAspects/#/components/date-time-picker#date-time-picker
2. Click on the first Edit in Plunker link.
3. Open the browser console for the Plunker tab.
4.  Click on the calender icon.

Observation:
An error appears on the console.
ERROR TypeError: Cannot read property 'name' of undefined
    at timezoneComparator (date-time-picker.utils.ts:82)
    at tryCatcher (tryCatch.ts:7)
    at DistinctUntilChangedSubscriber._next (distinctUntilChanged.ts:111)
    at DistinctUntilChangedSubscriber.Subscriber.next (Subscriber.ts:102)
    at BehaviorSubject.Subject.next (Subject.ts:62)
    at BehaviorSubject.next (BehaviorSubject.ts:40)
    at DateTimePickerComponent.set [as timezone] (date-time-picker.component.ts:66)
    at updateProp (provider.ts:446)
    at checkAndUpdateDirectiveInline (provider.ts:182)
    at checkAndUpdateNodeInline (view.ts:429)

Expectation:
No error should appear on the console while picking the date.

**Comment by donna-marijne** [comment]
Thanks for your report! Could you tell me which browser and version you are seeing this error on? Anything else that would help us reproduce?

**Comment by praveen2k10** [comment]
I am using Chrome: Version 68.0.3440.84 (Official Build) (64-bit), @ux-aspects/ux-aspects@=1.5.9

**Comment by donna-marijne** [comment]
Are you seeing this error in your own application?

**Comment by praveen2k10** [comment]
Yes

**Comment by donna-marijne** [comment]
Could you update your packages as follows:
* `@ux-aspects/ux-aspects`: 1.6.0
* `@micro-focus/ux-aspects`: 1.6.0
* `@micro-focus/quantum-ux-aspects`: 1.0.30

Thanks

**Comment by praveen2k10** [comment]
I got the same error after updating it as following
@ux-aspects/ux-aspects: 1.6.0
@micro-focus/quantum-ux-aspects: 1.0.30

I am not using @micro-focus/ux-aspects, however even after adding @micro-focus/ux-aspects:1.6.0 
I am getting the same error.

**Comment by donna-marijne** [comment]
Can you create a plunker example which shows what your code is doing with this component?

**Comment by praveen2k10** [comment]
I am trying to run the exact example code that is indicated on the below indicated url: 
https://uxaspects.github.io/UXAspects/#/components/date-time-picker#date-time-picker

**Comment by donna-marijne** [comment]
Sorry but I don't see any errors occurring in that example. Could you use the [seed project](https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus-seed) and send me a repro case showing exactly what you are doing with this component?

**Comment by praveen2k10** [comment]
Closing as the issue has disappeared, I have made several changes however I could not pin point a specific change I did to fix it.
